[package]
name = "music-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
egui_extras = "0.28.1"
enum-iterator = "2.1.0"
env_logger = "0.11.5"
hsv = "0.1.1"
paste = "1.0.15"
rand = "0.8.5"
rodio = "0.19.0"
rustysynth = "1.3.1"
